Products/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('categorytable/', views.categorytable,name="categorytable"),
    path('AddCategory/', views.AddCategory, name="AddCategory"),
    path('delete_Category/<int:id>/', views.delete_Category, name="deleteCategory"),
    path('Update_Category/<int:id>/', views.Update_Category, name="UpdateCategory"),
    path('ProductTable/',views.ProductTable,name="ProductTable"),
    path('AddProduct/',views.AddProduct,name="AddProduct"),
    path('delete_Product/<int:id>/', views.delete_Product, name="deleteProduct"),
    path('Update_Product/<int:id>/', views.Update_Product, name="UpdateProduct"),
    path('AddItem/',views.AddItem,name="AddItem"),
    path('ItemTable/',views.ItemTable,name="ItemTable"),
    path('delete_Item/<int:id>/', views.delete_Item, name="deleteItem"),
    path('Update_Item/<int:id>',views.Update_Item, name="UpdateItem"),
    path('Items/', views.Items, name='Items'),
    path('SearchResultsView/', views.SearchResultsView, name="search_results"),
    path('AllProducts/',views.AllProducts, name="AllProducts"),
    path('ItemStatus/<int:id>/',views.ItemStatus,name='ItemStatus'),
    path('shop/',views.shop,name="shop"),
    path('SearchResultsView/', views.SearchResultsView, name='search_results'),
    path('product_detail/<int:id>/',views.product_detail, name="product_detail"),
    path('details/<int:id>/', views.details_view,name="details_view"),

    ]

backend/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),


    ]

Products/models.py
from django.db import models
from mptt.models import MPTTModel
from mptt.fields import TreeForeignKey
from django.utils.safestring import mark_safe
# Create your models here.


class Category(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='image/')
    status = models.BooleanField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class MPTTMeta:
        order_insertion_by = ['title']

class Product(models.Model):
    category = TreeForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.CharField(max_length=255)
    price = models.FloatField()
    image = models.ImageField(upload_to='image/')
    status = models.BooleanField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="%s" style="width: 45px; height:45px;" />' % self.image.url)
        else:
            return 'No Image Found'

frontend/models.py
from django.db import models
from django.utils.safestring import mark_safe

class Country(models.Model):
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.name

class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, related_name="country_name", null=True)
    name = models.CharField(max_length=250, unique=True)


    def __str__(self):
        return self.name

class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.SET_NULL, related_name="state_name", null=True)
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.name


class Employee(models.Model):
    key = models.CharField(max_length=100,null=True)
    username = models.CharField(max_length=100)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')
    status = models.BooleanField(default=0)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    state = models.ForeignKey(State,on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    last_login = models.DateTimeField(auto_now_add=True)


    def image_tag(self):
        if self.document:
            return mark_safe('<img src="%s" style="width: 45px; height:45px;" />' % self.document.url)
        else:
            return 'No Image Found'

    def __str__(self):
        return self.username

class Post(models.Model):
    title = models.CharField(max_length=100)
    title_description = models.TextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    meta_description = models.TextField(max_length=100)
    status = models.BooleanField(default=0)
    image = models.ImageField(upload_to='img/')

    def __str__(self):
        return self.title

Products/forms.py
from django import forms
from .models import Category,Product

class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title','slug','status']

class UpdateCatForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'slug','description']



class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title','slug','price']


class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'slug','price']

class AddItemForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title','price','image','status']

class UpdateItemForm(forms.ModelForm):
    class Meta:
        model= Product
        fields = ['title','price','image','status']

Products/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Category,Product
from .forms import AddCategoryForm,UpdateCatForm,AddProductForm,UpdateProductForm,AddItemForm,UpdateItemForm
from math import ceil
from django.http import HttpResponse, JsonResponse
from rest_framework.parsers import JSONParser
from .serializers import ItemSerializer
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def AllProducts(request):
    products = Product.objects.all().filter(status=True)

    context = {
        'products': products,

    }
    return render(request, 'frontend/home1.html', context)

def Items(request):
    #items = Product.objects.all()
    allProds = []
    catprods = Product.objects.values('category', 'id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prod = Product.objects.filter(category=cat)
        n = len(prod)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        allProds.append([prod, range(1, nSlides), nSlides])
        params = {'allProds': allProds}
    return render(request, 'frontend/home.html', params)
    #context = {
       # 'items': items
   # }
    #return render(request, 'frontend/home.html', context)

def SearchResultsView(request):
        if request.method == "GET":
            search = request.GET.get('search')
            products = Product.objects.all().filter(title__icontains=search)
            return render(request, 'frontend/search.html', {'products': products})
def categorytable(request):
    cats = Category.objects.all()

    context = {
        'cats': cats,
    }
    return render(request, 'backend/categorytable.html', context)



def AddCategory(request):
    cats = Category.objects.all()
    if request.method == 'POST':
        fm = AddCategoryForm(request.POST)
        if fm.is_valid():
            title = fm.cleaned_data['title']
            slug = fm.cleaned_data['slug']
            status = fm.cleaned_data['status']
            Add = Category(title=title, slug=slug,status=status)
            Add.save()
            return redirect('categorytable')
    else:
        fm = AddCategoryForm()
    return render(request,'backend/addcategory.html',{'form':fm, 'cats':cats})


def delete_Category(request,id):
    if request.method == "POST":
        pi=Category.objects.get(pk=id)
        pi.delete()
        return redirect('categorytable')

def Update_Category(request,id):
    if request.method == "POST":
        pi = Category.objects.get(pk=id)
        fm = UpdateCatForm(request.POST, instance=pi)
        if fm.is_valid():
            fm.save()
            return redirect('categorytable')
    else:
         pi = Category.objects.get(pk=id)
         fm = UpdateCatForm(instance=pi)
    return render(request,'backend/updatecat.html',{'form':fm, 'pi':pi})



def ProductTable(request):
    products = Product.objects.all()

    context = {
        'products': products,
    }
    return render(request, 'backend/producttable.html', context)

def AddProduct(request):
    catprod = Category.objects.all()
    if request.method == "POST":
        form = AddProductForm(request.POST)
        if form.is_valid():
            title = request.POST['title']
            price = request.POST['price']
            slug = request.POST['slug']
            category = request.POST['category']
            category = get_object_or_404(Category, pk=category)
            prod = Product(title=title,price=price,slug=slug,category_id=category.id)
            prod.save()
            return redirect('ProductTable')
        else:
            form = AddProductForm(request.POST)
            return render(request, 'backend/AddProduct.html', {'form': form, 'catprod': catprod})

    else:
        form = AddProductForm()
        return render(request, 'backend/AddProduct.html', {'form': form, 'catprod': catprod})

def delete_Product(request,id):
    if request.method == "POST":
        pi=Product.objects.get(pk=id)
        pi.delete()
        return redirect('ProductTable')


def Update_Product(request,id):
    if request.method == "POST":
        pi = Product.objects.get(pk=id)
        fm = UpdateProductForm(request.POST, instance=pi)
        print(fm)
        if fm.is_valid():
            fm.save()
            return redirect('ProductTable')
    else:
         pi = Product.objects.get(pk=id)
         fm = UpdateProductForm(instance=pi)
    return render(request,'backend/UpdateProduct.html',{'form':fm, 'pi':pi})

def AddItem(request):
        Items = Category.objects.all()
        if request.method == "POST":
            form = AddItemForm(request.POST, request.FILES)
            if form.is_valid():
                title = request.POST['title']
                price = request.POST['price']
                image = request.FILES['image']
                category = request.POST['category']
                category = get_object_or_404(Category, pk=category)
                prod = Product(title=title, price=price, image=image,category_id=category.id)
                prod.save()
                return redirect('ItemTable')
            else:
                form = AddItemForm(request.POST)
                return render(request, 'backend/AddItem.html', {'form': form, 'Items': Items})

        else:
            form = AddItemForm()
            return render(request, 'backend/AddItem.html', {'form': form, 'Items': Items})


def ItemStatus(request,id):
    products = Product.objects.get(id=id)
    if products.status:
        products.status = False
    else:
        products.status = True
    products.save()
    products = Product.objects.all()
    return render(request, 'backend/ItemTable.html', {'products': products})


def ItemTable(request):
    products = Product.objects.all()

    context = {
        'products': products,
    }
    return render(request, 'backend/ItemTable.html', context)


def delete_Item(request,id):
    if request.method == "POST":
        pi=Product.objects.get(pk=id)
        pi.delete()
        return redirect('ItemTable')

def Update_Item(request,id):
    if request.method == "POST":
        pi = Product.objects.get(pk=id)
        fm = UpdateItemForm(request.POST, request.FILES, instance=pi)
        if fm.is_valid():
            fm.save()
            return redirect('ItemTable')
    else:
         pi = Product.objects.get(pk=id)
         fm = UpdateItemForm(request.FILES,instance=pi)
    return render(request,'backend/UpdateItem.html',{'form':fm, 'pi':pi})

def shop(request):
    products = Product.objects.all().filter(status=True)
    categories = Category.objects.all()
    context = {
        'products': products,
        'categories':categories,
    }
    return render(request,'frontend/Product.html',context)

def SearchResultsView(request):
        if request.method == "GET":
            search = request.GET.get('search')
            products = Product.objects.all().filter(title__icontains=search)
            return render(request, 'frontend/search.html', {'products': products})


def product_detail(request,id):
    category = Category.objects.all()
    product = Product.objects.filter(pk=id)
    context = {
        'category':category,
        'product':product,
    }
    return render(request, 'frontend/product_detail.html',context)

@csrf_exempt
def details_view(request,id):
    try:
        products = Product.objects.get(pk=id)
    except Product.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = ItemSerializer(products)
        return JsonResponse(serializer.data)

    elif request.method == "PUT":
        data = JSONParser().parse(request)
        serializer = ItemSerializer(products, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.error, status=400)

backend/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'backend/dashboard.html')

templates/backend/ContentTable.html
{% include 'backend/sidebar.html' %}
{% load static %}
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css">
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css
" rel="stylesheet" type="text/css">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Post Setting</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Settings</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->

    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Settings</h3>
            </div>

              {% if content %}
            <div class="card-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
              <tr>
                  <th>Id</th>
                  <th>Title</th>
                  <th>Title_Description</th>
                  <th>Meta_Description</th>
                  <th>Content</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for ct in content %}
                <tr>
                    <td>{{ct.id}}</td>
                    <td>{{ct.title}}</td>
                    <td>{{ct.title_description}}</td>
                    <td>{{ct.meta_description}}</td>
                    <td>{{ct.content}}</td>
                       <td><img {% if ct.image %} src="{{ct.image.url}}" style="height:50px !important; width:50px;" {% endif %}></br></td>
                    <td>{{ct.status}}</td>
                    <td>
                        <a href="{% url 'UpdatePost' ct.id %}">
                            <button class="btn btn-info">
                            <i class="fa fa-edit"></i>
                            </button>
                        </a>
                        <form action="{% url 'deletepost' ct.id %}" method="POST" class="d-inline">
                            {% csrf_token %}

                            <button class="btn btn-danger"  onclick="return confirm('Are you sure you want to delete this?')">
                            <i class="fa fa-trash"></i>
                            </button>
                             </form>
                            <a href="{% url 'PostStatus' ct.id %}">
                         <button class="btn btn-danger">
                            <i class="fa fa-ban"></i>
                         </button>
                               </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
                {% else %}
                <h4>No Recored</h4>
                {% endif %}
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{5 static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- page script -->
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
   <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
   <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
     $('#example2').DataTable({
    pageLength: 5,
    filter: true,
    deferRender: true,

    scrollCollapse: true,
    scroller: true
});
 </script>
 <!-- $(function () {
    $("#example2").DataTable({
      "responsive": true,
      "autoWidth": true,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": true,
      "responsive": true,
    });
  });-->

</body>
</html>

templates/backend/UpdateItem.html
{% include 'backend/sidebar.html' %}
{% load static %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Update Form</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Update Form</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Update Item</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="" method="POST" role="form" enctype="multipart/form-data">
                  {% csrf_token %}
        <div class="card-body">
            <div class="">
                <label for="id_title">Title:</label>
                <input type="text" name="title"  value="{{pi.title}}" class="vTextField" maxlength="255"  id="id_title" required>
            </div>

        </div>

      <div class="form-row field-price">
          <div>
              <label>Price:</label>
              <input type="text" name="price" value="{{pi.price}}" maxlength="255"   required>
          </div>
      </div>
       <div class="form-row field-image">
            <div>
                <label class="required">Image</label>
                <input type="file" value="{{pi.image.url}}" name="image" step="any" required>
                <img {% if pi.image %}  src="{{pi.image.url}}" width="50px;" {% endif %}>
            </div>

        </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
            </div>
            <!-- /.card -->

            <!-- Form Element sizes -->

  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<script type="text/javascript">
$(document).ready(function () {
  bsCustomFileInput.init();
});
</script>
</body>
</html>

templates/backend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Title</title>{% endblock title %}
</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

templates/backend/logout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
    {% load static %}
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700' %}" rel="stylesheet">
</head>
<body>

{% include 'backend/login.html'%}

</body>

templates/backend/password_reset_complete.html
{% extends 'backend/base.html' %}

{% block title %}Password reset complete{% endblock %}

{% block content %}
<h1>Password reset complete</h1>
<p>Your new password has been set. You can log in now on the <a href="{% url 'login' %}">log in page</a>.</p>
{% endblock %}

templates/backend/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.email}} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}

templates/backend/updatedata.html
{% include 'backend/sidebar.html' %}
{% load static %}
{% if message %}
{{message}}
{% endif %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Update Form</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Update Form</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Update Employee</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="" method="POST" role="form">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputUsername">UserName</label>
                    <input type="text" name="username" value="{{pi.username}}" class="form-control" id="exampleInputUsername" placeholder="Enter email">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputFirstname">Firstname</label>
                    <input type="text" name="firstname" value="{{pi.firstname}}" class="form-control" id="exampleInputFirstname" placeholder="Password">
                  </div>
                    <div class="form-group">
                    <label for="exampleInputLastname">Lastname</label>
                    <input type="text" name="lastname" value="{{pi.lastname}}" class="form-control" id="exampleInputLastname" placeholder="Password">
                  </div>
                    <div class="form-group">
                    <label for="exampleInputEmail">Email</label>
                    <input type="text" name="email" value="{{pi.email}}" class="form-control" id="exampleInputEmail" placeholder="Password">
                  </div>
                  <div>
                <div>
            <label for="id_country" class="col-md-3">Country:</label>
              <select name="country" class="form-control col-md-9" id="id_country" onchange="getStates(this.value)">
                  {% if i.name == pi.country.name %}
         <option value="{{pi.country.name}}"  selected>-- Select Country --</option>
                  {% else %}
            {% for i in countries %}
        <option value="{{i.id}}">{{i.name}}</option>
                  {% endfor %}
                  {% endif %}

</select></div>
          <p><label for="id_country">State:</label>
              <select name="state" id="id_state" class="form-control col-md-9" onchange="getCity(this.value)">
                  <option value="" selected >-- Select State --</option>


</select></p>
          <p><label for="id_country">City:</label>
              <select name="city" id="id_city" class="form-control col-md-9">
             <option value="" selected="">-- Select City ---</option>
              </select>
          </p>
                </div>

                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
            </div>
            <!-- /.card -->

            <!-- Form Element sizes -->

  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<script type="text/javascript">
$(document).ready(function () {
  bsCustomFileInput.init();
});
</script>
<script type="text/javascript">

getStates({{pi.country.id}})
    function getStates(id) {
        $.ajax({
            type: "GET",
            url: "/stateFetch/" + id,
            success: function (data) {
            console.log(data);
                if(data.length > 0) {
                    $('#id_state').empty();
                    $.each(data, function(key, value){
                        if(value.pk == {{pi.state.id}}) {
                            $('#id_state').append('<option selected="selected" value="'+ value.pk +'">'+ value.fields.name +'</option>');
                        } else {
                            $('#id_state').append('<option value="'+ value.pk +'">'+ value.fields.name +'</option>');
                        }
                    });
                } else {
                    $('#id_state').empty();
                }
            },
        });
        return true;
    }

getCity({{pi.state.id}});

    function getCity(id) {
        $.ajax({
            type: "GET",
            url: "/cityFetch/" + id,
            success: function (data) {
                console.log(data.length);
                if(data.length > 0) {
                    $('#id_city').empty();
                    $.each(data, function(key, value){
                    if(value.pk == {{pi.city.id}}) {
                        $('#id_city').append('<option selected value="'+ value.pk +'">'+ value.fields.name +'</option>');
                        } else {
                        $('#id_city').append('<option value="'+ value.pk +'">'+ value.fields.name +'</option>');
                        }
                    });
                } else {
                    $('#id_city').empty();
                }
            },
        });
        return true;
    }
</script>
</body>
</html>